#!/usr/bin/env python3
"""Post review results to GitHub PR."""

import os
import sys
import yaml
import requests
from pathlib import Path


def load_reviews(submission_id: str) -> dict:
    """Load all reviews including meta-review."""
    review_dir = Path("reviews") / submission_id
    reviews = {}

    for review_file in review_dir.glob("*.yaml"):
        agent = review_file.stem
        with open(review_file) as f:
            reviews[agent] = yaml.safe_load(f)

    return reviews


def format_review_comment(submission_id: str, reviews: dict) -> str:
    """Format reviews as GitHub markdown comment."""
    meta = reviews.get("meta-review", {})
    decision = meta.get("decision", "pending").upper()

    # Decision emoji
    emoji = {
        "ACCEPT": "✅",
        "MINOR_REVISION": "📝",
        "MAJOR_REVISION": "🔄",
        "REJECT": "❌"
    }.get(decision, "⏳")

    comment = f"""# {emoji} Review Complete: {decision}

**Submission ID:** {submission_id}

---

## Summary

"""

    # Add score breakdown
    if "synthesis" in meta:
        synthesis = meta["synthesis"]
        if "weighted_average" in synthesis:
            comment += f"**Weighted Average Score:** {synthesis['weighted_average']:.1f}/5.0\n\n"

        if "score_breakdown" in synthesis:
            comment += "| Agent | Score |\n|-------|-------|\n"
            for agent, score in synthesis["score_breakdown"].items():
                comment += f"| {agent.title()} | {score:.1f} |\n"
            comment += "\n"

    # Add rationale
    if "rationale" in meta:
        comment += f"""## Decision Rationale

{meta['rationale']}

"""

    # Add action items
    if "author_action_items" in meta and meta["author_action_items"]:
        comment += "## Action Items\n\n"
        for item in meta["author_action_items"]:
            if isinstance(item, dict):
                priority = item.get("priority", "recommended")
                action = item.get("action", "")
                icon = "🔴" if priority == "required" else "🟡"
                comment += f"- {icon} **{priority.title()}**: {action}\n"
            else:
                comment += f"- {item}\n"
        comment += "\n"

    # Add individual reviews
    comment += "---\n\n## Detailed Reviews\n\n"

    for agent in ["technical", "domain", "ethics", "clarity"]:
        if agent in reviews:
            review = reviews[agent]
            comment += f"""<details>
<summary><strong>{agent.title()} Review</strong> (Score: {review.get('scores', {}).get('overall', 'N/A')})</summary>

"""
            if "evaluation" in review:
                eval_data = review["evaluation"]
                if "summary" in eval_data:
                    comment += f"**Summary:** {eval_data['summary']}\n\n"

                if "strengths" in eval_data:
                    comment += "**Strengths:**\n"
                    for s in eval_data["strengths"]:
                        comment += f"- {s}\n"
                    comment += "\n"

                if "weaknesses" in eval_data:
                    comment += "**Weaknesses:**\n"
                    for w in eval_data["weaknesses"]:
                        comment += f"- {w}\n"
                    comment += "\n"

            comment += f"**Recommendation:** {review.get('recommendation', 'N/A')}\n\n"
            comment += "</details>\n\n"

    # Footer
    comment += """---

*This review was generated by the Agentic Journal multi-agent review system.
Reviews are AI-generated and should be evaluated critically.*

**Links:** [Review Process](https://akz4ol.github.io/agentic-journal/about/review-process/) | [Disclaimer](https://akz4ol.github.io/agentic-journal/about/disclaimer/)
"""

    return comment


def post_comment(pr_number: int, comment: str):
    """Post comment to GitHub PR."""
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY", "akz4ol/agentic-journal")

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }

    response = requests.post(url, headers=headers, json={"body": comment})

    if response.status_code == 201:
        print(f"Comment posted successfully")
    else:
        print(f"Failed to post comment: {response.status_code}")
        print(response.text)


def main():
    submission_id = os.environ.get("SUBMISSION_ID")
    pr_number = os.environ.get("PR_NUMBER")

    if not submission_id or not pr_number:
        print("Error: SUBMISSION_ID and PR_NUMBER required")
        sys.exit(1)

    print(f"Preparing notification for {submission_id} on PR #{pr_number}")

    # Load reviews
    reviews = load_reviews(submission_id)
    print(f"Loaded {len(reviews)} reviews")

    # Format comment
    comment = format_review_comment(submission_id, reviews)
    print(f"Comment length: {len(comment)} characters")

    # Post to PR
    post_comment(int(pr_number), comment)


if __name__ == "__main__":
    main()
